-- SQL
DROP TABLE IF EXISTS book;
CREATE TABLE IF NOT EXISTS book (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255),
  published_date INTEGER,
  pages INTEGER,
  summary TEXT,
  last_modified TIMESTAMP WITH TIME ZONE,
  version BIGINT
);